### PR TITLE
Feature/cerati ensure only one schedule v4

### PR DESCRIPTION
**Pull request by cerati**
Based on discussions at the LCM today, I am opening a PR for the version preserving the "lazy" feature and using mutex in the update functions.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by cerati** [comment]
are these CI failures expected? (this may be what Lynn referred to during the meeting yesterday)

**Comment by lgarren** [comment]
@cerati  the DUNE failure should be investigated.  Only argoneut and DUNE have updated to larsoft v09_62_00.  The uboone, icarus, and sbnd CI builds will fail until the experiments catch up.  lariat is hopelessly out of date and can be ignored.

**Comment by cerati** [comment]
that DUNE CI test seems to be failing starting from an earlier trigger than mine? dune_ci/14319 - not sure that that is

**Comment by lgarren** [comment]
@cerati please have a look at https://dbweb8.fnal.gov:8443/LarCI/app/ns:uboone/storage/docs/2022/11/03/builduBooNE%23atrMq0O.log  
There are build failures when compiling against this PR.

**Comment by cerati** [comment]
Thanks. I think there are two solutions. Let me tag @knoepfel and @hgreenlee to gather input. 

We discussed previously to move some of the functions triggering updates to private within the provider, to make the interface thread safe and avoid random code calling them. We added the service as a friend class to the provider so that it can all the private functions.

There are two options to move forward:
1. Add also UbooneChannelStatusService as friend class in the SIOVChannelStatusProvider
2. Move back the functions to public and rely on the mutex for thread safety

Both work for me.

**Comment by knoepfel** [comment]
> There are two options to move forward:
>
> 1. Add also UbooneChannelStatusService as friend class in the SIOVChannelStatusProvider
> 2. Move back the functions to public and rely on the mutex for thread safety

@cerati, I recommend option 2 as the medium-term solution until concurrent caching is supported.  Although it's possible for someone to misuse the public functions, that's probably a better risk than having to specify all of the downstream services as friends.

**Comment by cerati** [comment]
Thanks @knoepfel , that was my inclination too. I will go ahead and update the PR accordingly.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
Results from a hand triggered uboone build:
https://dbweb8.fnal.gov:8443/LarCI/app/ns:uBooNE/view_builds/index?offset=0&builds=uboone_ci/8132&builds=

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
