### PR TITLE
Feature/cerati ensure only one schedule

### PR DESCRIPTION
**Pull request by cerati**
Pull request making SIOVChannelStatusProvider and SIOVDetPedestalService SHARED after inheriting from EnsureOnlyOneSchedule. This ensures that updates are at event boundaries so that it's thread safe for multithreading within one event. It is not thread safe across events and will throw an exception if executed with more than one schedule.

Currently under testing.

### CODE REVIEW

**Comment by knoepfel** [comment]
code-checks

**Comment by knoepfel** [comment]
trigger build

**Comment by knoepfel** [comment]
trigger build

There were some problems with the CI last week.

**Comment by lgarren** [comment]
@cerati @knoepfel  The latest round of CI test results are as expected.  uboone has not yet updated their code to use the latest larsoft release.

**Comment by lgarren** [comment]
closed in favor of #19

**Pull request closed without merging**
