### PR TITLE
Update LArG4ParticleFilter_module.cc

### PR DESCRIPTION
**Pull request by imranyusuff**
Added missing call to StartInTPCCheck

### CODE REVIEW

**Comment by absolution1** [comment]
approve

**Comment by knoepfel** [comment]
Do you expect this change to affect current results?

**Comment by imranyusuff** [comment]
> Do you expect this change to affect current results?

It will affect post G4 particle filtering. I am working with kaons which are starting in TPC post G4, and without this line I ended up with large number of events where kaons are not inside TPC.

**Comment by lgarren** [comment]
approve

**Pull request merged**
